### ISSUE TITLE
"UnhandledPromiseRejectionWarning: Error: Cannot subscribe this user: invalid OAuth credentials provided."

### ISSUE THREAD

**Issue by hoemon** [twitterdev/autohook#1]
Can't make the example script work with my provided oauth token and secret.

### Expected behavior

It should subscribe.

### Actual behavior

..but does not.

### Steps to reproduce the behavior

copy paste the example script provided - since it does not work as is, I've added two const variables:

const oauth_token = "mytoken"
const oauth_token_secret = "mytokensecret"

However, this returns the error

"UnhandledPromiseRejectionWarning: Error: Cannot subscribe this user: invalid OAuth credentials provided."

**Comment by taniele** [comment]
@hoemon can you reply with the entire snippet, or with a link to a public Gist containing the snippet you're using? This will help us greatly in order to better understand the issue. Be sure to remove the actual token/secrets.

**Comment by hoemon** [comment]
```
const { Autohook } = require('twitter-autohook');

(async start => {
  const webhook = new Autohook();
  
  // Removes existing webhooks
  await webhook.removeWebhooks();
  
  // Listens to incoming activity
  webhook.on('event', event => console.log('Something happened:', event));
  
  // Starts a server and adds a new webhook
  await webhook.start();
  
  // Subscribes to a user's activity
  await webhook.subscribe({oauth_token, oauth_token_secret});
})();
```

I have `.env.twitter` file in my home directory with the provided credentials.
There was a typo at the example script above - a forgotten parenthesis - I closed it

`event));`

**Comment by hoemon** [comment]
```
Getting webhooks…
(node:17291) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at getWebhooks (/home/tw/node_modules/twitter-autohook/index.js:90:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Autohook.removeWebhooks (/home/tw/node_modules/twitter-autohook/index.js:189:22)
    at async /home/tw/test.js:14:3
(node:17291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

..and this is the full error

**Comment by taniele** [comment]
@hoemon This may be happening because one of the configuration variables in your `.env.twitter` are not set or contain invalid characters. I suspect the `TWITTER_WEBHOOK_ENV` variable may be causing this issue.

What's the value for your `TWITTER_WEBHOOK_ENV` variable in your `.env.twitter`? This value must match a valid environment in your app configuration in the [Developer dashboard](https://developer.twitter.com/en/account/environments) under "Account Activity API". If you don't see "Account Activity API" in your app environment, you may need to create a dev environment.

**Comment by taniele** [comment]
@hoemon we haven't heard from you in a while so I'm assuming we can close this issue. The latest Autohook provides better handling of error messages so you should be able to dig further into the actual issue. Feel free to reopen if you need more help here.
