### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Simonl07** [twitterdev/autohook#13]
One line summary of the issue here.

Cannot start with `autohook -rs`

### Expected behavior

I stored my credentials in ~/.env.twitter, and ran `autohook -rs` but I am not able to start due to following errors:

### Actual behavior

```
Getting webhooks…
Removing webhooks…
(node:25498) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at /usr/local/share/.config/yarn/global/node_modules/twitter-autohook/cli.js:68:33
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:25498) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25498) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

### Steps to reproduce the behavior

1. Configure .env.twitter
2. run `autohook -rs`

I have also tried to pass credentials by command line but the same error appears

**Comment by iamdaniele** [comment]
@Simonl07 this should be resolved in v1.4.2, where you should get a more meaningful error message instead of the behavior you've experienced. Would you be able to get that version and confirm resolved?
