### ISSUE TITLE
Could not find a declaration for Module 'twitter-autohook'

### ISSUE THREAD

**Issue by Jerseyetr** [twitterdev/autohook#14]
Could not find a declaration file for module 'twitter-autohook'. '/Users/jerseyetr/Documents/Twitter-Bot/node_modules/twitter-autohook/index.js' implicitly has an 'any' type.
  Try `npm install @types/twitter-autohook` if it exists or add a new declaration (.d.ts) file containing `declare module 'twitter-autohook';`ts(7016)

As a noob, im not entirely sure what this means. I tried fixing with the recommended fix, but did not work.

**Comment by iamdaniele** [comment]
Hi @Jerseyetr, this likely means you're trying to use Autohook in TypeScript, is that correct? If that's the case, Autohook currently does not have any type declaration, so you may need to add the declaration manually to `.d.ts`.
