### ISSUE TITLE
Getting error while trying to use autohook to generate a webhook

### ISSUE THREAD

**Issue by Mikeac94** [twitterdev/autohook#16]
While runnning the index.js file, I get this error ==>

Getting webhooks…
Removing webhooks…
Registering https://4d2a94bf.ngrok.io/webhook as a new webhook…
ReferenceError: URL is not defined
    at setWebhook (/Users/mikeashleycedric/node_modules/twitter-autohook/index.js:169:20)
    at Autohook.start (/Users/mikeashleycedric/node_modules/twitter-autohook/index.js:287:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Mikeac94** [comment]
@iamdaniele please add const URL = require('url').URL; in your index.js file
and in every file where you're using new URL() method;

**Comment by iamdaniele** [comment]
@Mikeac94 thank you. Looking into this right now.

**Comment by iamdaniele** [comment]
@Mikeac94 this should be resolved in v1.4.2. Would you be able to get that version and confirm resolved?
