### ISSUE TITLE
Cannot subscribe to activities: Webhook URL must be defined to create subscriptions. Should this not be done automatically?

### ISSUE THREAD

**Issue by jason-james** [twitterdev/autohook#2]
I'm not able to successfully subscribe to my webhook using autohook.

### Expected behavior

I would expect autohook to automatically define the webhook URL for me and subscribe successfully.

### Actual behavior

It throws the error `Cannot subscribe to [my username's] activities: Webhook URL must be defined to create subscriptions. (Twitter code: 170).`

### Steps to reproduce the behavior

```
import { Autohook } from "twitter-autohook";

export default async function initWebhook(oauth_token, oauth_token_secret) {
  try {
    const webhook = new Autohook();

    // Removes existing webhooks
    await webhook.removeWebhooks();

    // Listens to incoming activity
    webhook.on("event", event => console.log("Something happened:", event));

    // Starts a server and adds a new webhook
    webhook.start();

    // Subscribes to a user's activity
    webhook.subscribe({ oauth_token, oauth_token_secret });
  } catch (e) {
    console.log(e);
  }
}

  initWebhook(
    process.env.TWITTER_ACCESS_TOKEN,
    process.env.TWITTER_ACCESS_TOKEN_SECRET
  );
```

Full error:

```
Registering https://480a3fc7.ngrok.io/webhook as a new webhook…
(node:106798) UnhandledPromiseRejectionWarning: Error: Cannot subscribe to [username] activities: Webhook URL must be defined to create subscriptions. (Twitter code: 170).
    at Autohook.subscribe (/)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:106798) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:106798) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Webhook created.
```

**Comment by taniele** [comment]
@jason-james I suspect this is happening because `await` is missing before `webhook.start()` and `webhook.subscribe()`, which causes `subscribe` to execute before `start` is done setting up the webhook URL. Can you try adding `await` and let us know if that solves the issue?

```js
import { Autohook } from "twitter-autohook";

export default async function initWebhook(oauth_token, oauth_token_secret) {
  try {
    const webhook = new Autohook();

    // Removes existing webhooks
    await webhook.removeWebhooks();

    // Listens to incoming activity
    webhook.on("event", event => console.log("Something happened:", event));

    // Starts a server and adds a new webhook
    await webhook.start();

    // Subscribes to a user's activity
    await webhook.subscribe({ oauth_token, oauth_token_secret });
  } catch (e) {
    console.log(e);
  }
}

  initWebhook(
    process.env.TWITTER_ACCESS_TOKEN,
    process.env.TWITTER_ACCESS_TOKEN_SECRET
  );
```

**Comment by jason-james** [comment]
@taniele Great! That worked, thanks.

I have a separate query, I guess you are the best person to ask...

Let's say I set up a webhook without Autohook and verify CRC correctly via NodeJs. The app which hosts the webbook is a React app deployed on Heroku. 

Could you please describe how I would subscribe to this webhook from a separate Python application? Am I correct in thinking the steps are:

1. Set up a basic web server in the Python app
2. Start server
3. Send POST request with auth to `https://api.twitter.com/1.1/account_activity/all/:env_name/webhooks.json`
4. Listen for POST requests at my heroku domain where the webhook is <- Step I am unsure of

I'm not sure how I would gain authentication to listen for the POST requests from a separate application/server.

**Comment by taniele** [comment]
@jason-james The [Twitter Community forums](https://twittercommunity.com) are the best place to ask questions not related to Autohook, including questions regarding webhooks (we're also usually much faster in addressing these questions).

To your point, your webhooks will need to correctly respond to a CRC check every time we send a CRC challenge (this happens when you first register your webhook, and periodically after that). You can refer to the [Securing webhooks page](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/guides/securing-webhooks.html) on our Developer Reference for all the requirements (plus a Python example).

**Comment by Mikeac94** [comment]
hi @iamdaniele , I am trying to use twitter-autohook to generate a webhook, while i try and use it. and run the index.js file. I get this error ==>
