### ISSUE TITLE
TypeError: Cannot destructure property `oauth_token` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by jokoast** [twitterdev/autohook#23]
I hard coded the credentials in my app.js to perform some test on Windows 10.

### Expected behavior

I assume it should run fine, but the webhook.subscribe() method asks for Oauth and i don't have them as the token and consumer_secret are those of my account/app.

I removed the oauth parameters as this :
`// Subscribes to a user's activity`
`await webhook.subscribe();` 

The Lambda character in the creation of the async anonymous function produced me an error btw

### Actual behavior

I have this error 
`(node:15380) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property oauth_token of 'undefined' or 'null'.`

Meaning that the .subscribe method wants parameters i can't give. 

### Steps to reproduce the behavior

Hard Code the credentials in app.js 

### More infos
Full output : 
```
Debugger listening on ws://127.0.0.1:5858/ac1e92bc-564b-411b-8d62-b589b7067b75
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Getting webhooks…
Removing webhooks…
Removing https://fe70d033.ngrok.io/webhook…
Registering https://c164966a.ngrok.io/webhook as a new webhook…
Webhook created.
(node:12588) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `oauth_token` of 'undefined' or 'null'.
    at Autohook.subscribe (D:\Coding\NodeJS\Twitter2Streamlabs\node_modules\twitter-autohook\index.js:296:19)
    at D:\Coding\NodeJS\Twitter2Streamlabs\app.js:23:19
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:12588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Full snipet :
```
const { Autohook } = require('twitter-autohook');

(async asyncaf => {
    const webhook = new Autohook({
        token: xxxxx,
        token_secret: xxxxx,
        consumer_key: xxxxx,
        consumer_secret: xxxxx,
        env: xxxxx,
        port: xxxxx
    });

    // Removes existing webhooks
    await webhook.removeWebhooks();

    // Listens to incoming activity
    webhook.on('event', event => console.log('Something happened:', event));

    // Starts a server and adds a new webhook
    await webhook.start();

    // Subscribes to a user's activity
    await webhook.subscribe();

})();
```

EDIT : 
I also tried using just the { screen_name: "xxx" } in the subscribe method, doesn't work either. Does this library handles self auth ?

**Comment by iamdaniele** [comment]
Hi @jokoast, I think this is happening because the call to `webhook.subscribe()` has no arguments. Autohook requires to pass an object to `webhook.subscribe()` with at least two fields:
```js
{
  oauth_token: '', // the token of the user you want to subscribe
  oauth_token_secret: '', // the token secret of the user you want to subscribe
}
```

When used as a library, Autohook does not automatically self subscribe (you can self subscribe from the CLI using the `-s` option). To subscribe your own user, use the values for `token` and `token_secret` you pass to the Autohook constructor this way:

```js
await webhook.subscribe({ oauth_token: '(the value from token)', oauth_token_secret: '(the value from token_secret)' });
```
