### ISSUE TITLE
Not able to get/listen data of incoming events 

### ISSUE THREAD

**Issue by nisarg1499** [twitterdev/autohook#26]
One line summary of the issue here.
After adding `webhook.on('event', async event => {console.log('You received an event!');
    });` line into the code, I am not getting any live activity of the subscribed user.

### Expected behavior
Live activity of subscribed user should be available. As soon as I follow someone, or do direct message than that activity of subscribed user should be available. 

### Actual behavior
Using current sample code mentioned [here](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/guides/twitter-account-activity-tutorial-autohook), while I do some activity at that time I am not able to see any activity data on my console.Whenever I perform a new activity from user's account, I am not able to see any event on the console.

### Steps to reproduce the behavior
Using ngrok as tunnel.
```
const { Autohook } = require('twitter-autohook');
require('dotenv').config();


(async start => {
  try {
    // console.log(process.env.TWITTER_ACCESS_TOKEN)
    // console.log(process.env.TWITTER_CONSUMER_SECRET)
    const webhook = new Autohook();
    
    // Removes existing webhooks
    // await webhook.removeWebhooks();
    
    // Starts a server and adds a new webhook
    await webhook.startServer();

    webhook.on('event', async event => {

        if (event.direct_message_events) {
            console.log("Heyyy");
          }
        console.log(event)
        console.log('You received an event!');
      });
    
    // webhook.unsubscribe(id)
    
    await webhook.subscribe({oauth_token: process.env.TWITTER_ACCESS_TOKEN, oauth_token_secret: process.env.TWITTER_ACCESS_TOKEN_SECRET}); 
    
    
  } catch (e) {
    // Display the error and quit
    console.error(e);
    process.exit(1);
  }
})();  
```

**Comment by iamdaniele** [comment]
@nisarg1499 try replacing `await webhook.startServer();` with `await webhook.start();`.

`startServer` initializes a local webserver but does not register the webhook with Twitter. `start` does both.

**Comment by nisarg1499** [comment]
I have my webboom registered that's why I used `await webhook.startServer();`. I have been registered to a users activity. But then I am not receiving any live activity log of that user.

**Comment by iamdaniele** [comment]
That's happening because the `event` listener is not activated when using your own webserver. In those configurations, simply handle the events directly from your webhook logic. If you're using Express for example, your `event` listener is basically the route associated to the webhook you registered. To see how to handle events when using an external webserver, refer to the [standalone server example](https://github.com/twitterdev/autohook/blob/master/examples/standalone-server.js#L9).

**Comment by iamdaniele** [comment]
We haven't heard in a while so I'll close this issue. Feel free to reopen or create a new issue if you need additional help.
