### ISSUE TITLE
 Cannot find module 'qs'

### ISSUE THREAD

**Issue by leocabeza** [twitterdev/autohook#31]
When using it as a node module, it throws because it couldn't find the `qs` dependency.

### Expected behavior

Not to throw

### Actual behavior

It throws:
![image](https://user-images.githubusercontent.com/2538304/83305296-1cfa8c80-a1c6-11ea-8f22-0b6d1dbe81e2.png)

### Steps to reproduce the behavior

install as a node module with `npm install twitter-autohook --save`, then:
```js
import { Autohook } from 'twitter-autohook';

new Autohook({
  token: process.env.TWITTER_ACCESS_TOKEN,
  token_secret: process.env.TWITTER_ACCESS_TOKEN_SECRET,
  consumer_key: process.env.TWITTER_CONSUMER_KEY,
  consumer_secret: process.env.TWITTER_CONSUMER_SECRET,
  env: process.env.TWITTER_WEBHOOK_ENV
});
```

**Comment by leocabeza** [comment]
I think this is the line it throws: https://github.com/twitterdev/autohook/blob/f579e1f0ba9075815d8e4da37b59e15f9044417f/client/index.js#L5

Maybe this is a typo and wanted to use the `querystring` module such as:
`const qs = require('querystring');`

or maybe we want to add the `qs` package as a dependency on the `package.json` file

**Comment by iamdaniele** [comment]
Thank you @leocabeza. I merged your PR and will be including into the next release.
