### ISSUE TITLE
Twitter Autohook silently fails to receive furthur reqests after a few hours

### ISSUE THREAD

**Issue by sachushaji** [twitterdev/autohook#36]
I have successfully integrated twitter autohook and every functionality seems working fine. But after a few hours, it silently stops taking requests without throwing much error. 
### Expected behavior
It should work perfectly after the server is up even after several hours and should error out if something failed

### Actual behavior
Autohook get subscribed and after a few hours it doesn't receive any response

### Steps to reproduce the behavior
Configure autohook and deploy to a server. After few hours it doesn't accept webhook requests.

## Error Logs
My server is configured to automatically restart if the application errors out. Sometimes, I see this error coming up

![image](https://user-images.githubusercontent.com/15767732/88535128-0a1a0200-d027-11ea-88e1-c4326344a539.png)

The codebase is opensource. So you can also view my implementation [here](https://github.com/HelixNetwork/helix-twitter-bot/blob/master/index.js)

**Comment by yash-atreya** [comment]
@sachushaji Were you able to solve this?

**Comment by sachushaji** [comment]
@yash-atreya, I refactored the code by using this [example](https://github.com/twitterdev/autohook/blob/master/examples/standalone-server.js) code in the repo yesterday. It's now listening for a few more hours, But again facing the same issue today. It's not clearly consistent to say when exactly this is happening. The above errors in the error logs are still happening. I was wondering is it because I'm using free sandbox API ?

**Comment by yash-atreya** [comment]
@sachushaji Yes I am also using the code from the example. Facing the same issue as I am also on the Free API.

**Comment by james-muriithi** [comment]
Check this, might help you 

https://github.com/twitterdev/autohook/issues/21#issuecomment-667103718

**Comment by sachushaji** [comment]
I added auth token to ngrok, and it seemed stable now. The reason I think it was failing was that ngrok connections without auth tokens will be terminated after a certain limited time. With auth token,I suppose it will be a more stable connection

**Comment by yash-atreya** [comment]
@sachushaji Can you elaborate which auth tokens did you add to ngrok ?

**Comment by sachushaji** [comment]
I have made a fix at PR #37. You just need to go to ngrok.com, configure account and use the authtoken before connecting to ngrok as per the example (code)[https://github.com/HelixNetwork/helix-twitter-bot/blob/master/index.js]
