### ISSUE TITLE
Using autohook without ngrok

### ISSUE THREAD

**Issue by pbshgthm** [twitterdev/autohook#40]
Is there a way to use autohook without ngrok? I'm deploying it on a VPS.

**Comment by iamdaniele** [comment]
Yes, you can use Autohook without ngrok. 

Autohook only uses ngrok to expose its local server to the internet. When you deploy to a server that's already accessible from the internet, you should already have both a public server and a public URL, and that means you don't need ngrok.

Your server's router must serve a webhook URL. If you're using Express, this is very simple to implement. Let's assume your webhook URL is `https://example.com/webhook/twitter`:

```js
app.all('/webhook/twitter', async (request, response) => {
  // Fulfills the CRC check when Twitter sends a CRC challenge
  if (request.query.crc_token) {
    const signature = validateWebhook(request.query.crc_token, {consumer_secret: process.env.TWITTER_CONSUMER_SECRET});
    response.json(signature);
  } else {
    // Send a successful response to Twitter
    response.sendStatus(200);
    // Add your logic to process the event
    console.log('Received a webhook event:', request.body);
  }
});
```

When the server starts, you will not need to start ngrok. Instead, simply pass the URL to your Heroku instance to Autohook.

```js
const WEBHOOK_URL = 'https://example.com/webhook/twitter';

const listener = server.listen(process.env.PORT, async () => {
  const webhook = new Autohook();
  await webhook.start(WEBHOOK_URL);

  console.log(`Your app is listening on port ${listener.address().port}`);
});
```

When passing a value to `webhook.start()`, ngrok will not start, and your webhook route will be used instead.

**Comment by pbshgthm** [comment]
Thank you for the clear explanation. I got it working. However, I'm not able to read the body of the request object. I just receive a request object on account activity even. Is request.body the right way? Am I missing something else? I'm using express btw. This is my implementation. I'm getting undefined at request.body.

```js
const express = require('express')
const { Autohook,validateWebhook} = require('twitter-autohook');

const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.all('/webhook/twitter', async (req, res) => {
  	if(req.query.crc_token){
    	        const signature = validateWebhook(req.query.crc_token, {
			consumer_secret: process.env.TWITTER_CONSUMER_SECRET
		});
    	        res.json(signature);
  	}else{
		res.sendStatus(200);
    	        console.log('Received a webhook event');
		console.log(req.body)
	}
});



const listener = app.listen(port, async () => {
	
	const webhook = new Autohook();
	await webhook.removeWebhooks();  
	await webhook.start(process.env.WEBHOOK_BASE_URL+'/webhook/twitter');
        await webhook.subscribe({
		oauth_token: process.env.TWITTER_ACCESS_TOKEN,
		oauth_token_secret: process.env.TWITTER_ACCESS_TOKEN_SECRET
	}); 
	
	console.log(`Your app is listening on port ${listener.address().port}`);
});
```

**Comment by iamdaniele** [comment]
I see this is being asked in #41, and I left a comment there. In the future, feel free to keep commenting on closed issues so we can reopen and keep track accordingly.
