### ISSUE TITLE
How to avoid autohook - ngrok pitfalls ?

### ISSUE THREAD

**Issue by orgicus** [twitterdev/autohook#42]
I've followed the instructions from the [Twitter autohook tutorial](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/subscribe-account-activity/guides/twitter-account-activity-tutorial-autohook) and this repo's readme, however I still managed to get stuck with tunnelling/ngrok related issues.

### Expected behavior

Expected behaviours is seeing twitter event data and no errors

### Actual behavior

Instead of event data I get connection reset or failed to start tunnel errors:
```javascript
node index.js
Getting webhooks…
Removing webhooks…
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:200:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

node index.js
Getting webhooks…
Removing webhooks…
{
  error_code: 103,
  status_code: 502,
  msg: 'failed to start tunnel',
  details: { err: 'remote gone away' }
}
```

### Steps to reproduce the behavior

0. `npm install twitter-autohook`
1. populate %HOMEPATH%\.env.twitter:

```bash
TWITTER_CONSUMER_KEY="### my API key"
TWITTER_CONSUMER_SECRET="### my API key secret"
TWITTER_ACCESS_TOKEN="### my Access token"
TWITTER_ACCESS_TOKEN_SECRET="### my Access token secret"
TWITTER_WEBHOOK_ENV="dev" (as defined at https://developer.twitter.com/en/account/environments as Dev environment label)
NGROK_AUTH_TOKEN="### my ngrok auth token"
```

2. paste example code to index.js:

```javascript

const { Autohook } = require('twitter-autohook');

(async start => {
  try {
    const webhook = new Autohook();
    
    // Removes existing webhooks
    await webhook.removeWebhooks();
    
    // Starts a server and adds a new webhook
    await webhook.start();
    
    // Subscribes to your own user's activity
    await webhook.subscribe({oauth_token: process.env.TWITTER_ACCESS_TOKEN, oauth_token_secret: process.env.TWITTER_ACCESS_TOKEN_SECRET});  
  } catch (e) {
    // Display the error and quit
    console.error(e);
    process.exit(1);
  }
})();  
```

3. Run code and observe error

I'm using node v12.14.1 on Windows 10 at the moment.

The project looks great and support outstanding 👏 
I feel I'm missing a trick with ngrok here.
Any hints/tips to progress are well apreciated!

Many thanks,
George

**Comment by iamdaniele** [comment]
I can confirm this is an issue with ngrok. Things to check:

- Does `ngrok http 80` work correctly?
- Is there a firewall or other software enabled on your machine that may block or interfere with ngrok's tunneling?
- Is there another ngrok process running on the machine?
- Does the problem occur if `NGROK_AUTH_TOKEN` is not provided?

**Comment by orgicus** [comment]
Hi @iamdaniele 

Thank you for the swift reply.
I've tested a few of the things you've recommended:

- `ngrok http 80` works correctly (I've started a generic http server on port 80 and tested connection via ngrok tunnel and that worked)
- I've double checked firewall, allowed the port mentioned in console, even temporarily tried completely turning off firewall to change, but it didn't seem to make a difference (got same errors)
- I checked: no other ngrok process running
- it doesn't seem to make a difference if I ommit `NGROK_AUTH_TOKEN`

The strange thing now is I get a different auth error:
```javascript
Getting webhooks…
Removing webhooks…
Registering https://56fd14d27cbc.ngrok.io/webhook as a new webhook…
Cannot create webhook: AuthenticationError: Application cannot perform write actions. Contact Twitter Platform Operations through https://help.twitter.com/forms/platform. (HTTP status: 403, Twitter code: 261)
    at tryError (C:\Users\george.profenza\Downloads\gp\twitter-api-test\node_modules\twitter-autohook\errors\index.js:53:12)
    at Autohook.setWebhook (C:\Users\george.profenza\Downloads\gp\twitter-api-test\node_modules\twitter-autohook\index.js:208:19)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Autohook.start (C:\Users\george.profenza\Downloads\gp\twitter-api-test\node_modules\twitter-autohook\index.js:277:7)
    at async C:\Users\george.profenza\Downloads\gp\twitter-api-test\index.js:21:5 {
  name: 'AuthenticationError',
  code: 261
}
AuthenticationError: Application cannot perform write actions. Contact Twitter Platform Operations through https://help.twitter.com/forms/platform. (HTTP status: 403, Twitter code: 261)
    at tryError (C:\Users\george.profenza\Downloads\gp\twitter-api-test\node_modules\twitter-autohook\errors\index.js:53:12)
    at Autohook.setWebhook (C:\Users\george.profenza\Downloads\gp\twitter-api-test\node_modules\twitter-autohook\index.js:208:19)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Autohook.start (C:\Users\george.profenza\Downloads\gp\twitter-api-test\node_modules\twitter-autohook\index.js:277:7)
    at async C:\Users\george.profenza\Downloads\gp\twitter-api-test\index.js:21:5 {
  name: 'AuthenticationError',
  code: 261
}
```

What should I try ?

**Comment by iamdaniele** [comment]
No problem! I think you got past the ngrok error, but now you are receiving an API error. `AuthenticationError` is a Twitter error. The most likely cause is that your app is configured with Read only permissions. The [error message explanation page](https://developer.twitter.com/en/support/twitter-api/error-troubleshooting#:~:text=Code%20261%20-%20App%20cannot%20perform,token%20and%20access%20token%20secret.) should guide you to fix the issue (simply navigate to your [Developer account](https://developer.twitter.com/apps), select your app, then select Read, Write, and Direct Messages under App permissions). You will need to regenerate your keys and tokens, and you will need to use the updated information in your `.env.twitter`.

**Comment by orgicus** [comment]
That was the missing piece of the puzzle (read + wrtite + DM, regen. tokens) !

Thank you so much 🙏
