### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by dan89farhan** [twitterdev/autohook#45]
A one-line summary of the issue here.
Want to use the same webhook URL for different clients(different credentials)

getting following errors:

Cannot create webhook: AuthenticationError: Too many resources already created. (HTTP status: 400, Twitter code: 214)

### Expected behavior

I am providing different configs while creating the webhook without removing earlier webhooks

### Actual behavior

It is removing existing webhooks even I am providing different config while creating the webhook

Code: 

const webhook = new Autohook({
    token: this.config.TWITTER_ACCESS_TOKEN,
    token_secret: this.config.TWITTER_ACCESS_TOKEN_SECRET,
    consumer_key: this.config.TWITTER_CONSUMER_KEY,
    consumer_secret: this.config.TWITTER_CONSUMER_SECRET,
    // ngrok_secret: 'value', // optional
    env: this.config.TWITTER_WEBHOOK_ENV,
});
// Removes existing webhooks
await webhook.removeWebhooks();

// Starts a server and adds a new webhook
const startWebhook = await webhook.start(webhookUrl);

// Subscribes to your own user's activity
const subscribeData = await webhook.subscribe(
    {
        oauth_token: this.config.TWITTER_ACCESS_TOKEN,
        oauth_token_secret: this.config.TWITTER_ACCESS_TOKEN_SECRET
    }
);

Here the webhook URL is 

/webhook/twitter/:campaing_id

where campaign_id will be different for different clients
### Steps to reproduce the behavior

use the above code with different credentials.

**Comment by iamdaniele** [comment]
It's possible that this is happening because `await webhook.removeWebhooks();` is still present in your code. Did you try and remove that line and see if that solves the issue?

**Comment by iamdaniele** [comment]
Closing this issue as it hasn't seen a reply in a long time. Feel free to reopen if needed.
