### ISSUE TITLE
Sometimes webhook not responding

### ISSUE THREAD

**Issue by felangga** [twitterdev/autohook#9]
After a while running, sometimes the webhook event listener not returning any mention or Direct Message. Is it any quota or limit time to connect for the free user?

**Comment by iamdaniele** [comment]
Hi @felangga, can you please share more details? For example, do you see Autohook failing with any error when this happens? Are you using your own webhook server, or are you running Autohook with its default configuration?
Account Activity does not have a time limit. If you're running Autohook on your local development environment, the CRC challenge may fail if your connection lags which. This would invalidate your local webhook, which means you won't receive any more events unless you re-register the webhook.

**Comment by felangga** [comment]
There is no error or something that I can report. It's just stop responding to any activity. I tried to mention and direct message but no respond. 
I'm using this library same as the tutorial said. 
Now, I'm scheduling to re-registering the webhook to avoid this from happening again.

**Comment by zuzak** [comment]
I get this issue as well. After about thirty events -- sometimes twenty, sometimes forty -- the server seems to stop receiving further events. If I remove the webhook and add a new one, the events start happening again immediately for a further 30 or so events.

I've ended up adding a timeout so that if no events are received within 60 seconds, we restart. That's "solved" the problem in the short term, but is hardly a sustainable solution.

**Comment by iamdaniele** [comment]
Just wanted to circle back on this issue. To better understand the problem, can you provide us with the following details:

1. How frequent is the issue? Does it happen in specific circumstances?
2. Where does this issue happen? Is this happening on your local environment, or is it happening on a deployed location?
3. Does this happen while using ngrok?
4. Does this happen while using your own web server?

**Comment by iamdaniele** [comment]
@felangga we haven't heard from you in a while so I'm going to close this for now. Please feel free to reopen if you have more details on the issue.

**Comment by zuzak** [comment]
Looks like this is happening with ngrok whenever I get a particularly large number of webhook events. After between 30 and 40 events, ngrok ceases sending me any events. I have hacky code to restart everything once the server's been silent for a minute or so, which keeps me below the Twitter API limit, but means I never receive a significant percentage of webhook events if a tweet is particularly popular.
